repos:
  # 🔹 Basic hygiene (spaces, newlines)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  # 🔹 Terraform checks
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.88.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate

  # 🔹 Python formatting (Black)
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black

  # 🔹 Python linting (Ruff)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
