name: Terraform & Python Validation

on:
  push:
  pull_request:

jobs:
  terraform-and-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ----- Terraform checks for every projects/*/terraform dir -----
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Find terraform directories
        id: findtf
        run: |
          mapfile -t TF_DIRS < <(find projects -type d -name terraform | sort || true)
          echo "dirs<<EOF" >> $GITHUB_OUTPUT
          for d in "${TF_DIRS[@]}"; do echo "$d"; done >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Terraform fmt/validate
        if: steps.findtf.outputs.dirs != ''
        run: |
          set -euo pipefail
          while IFS= read -r d; do
            echo "▶ Checking $d"
            (cd "$d" && terraform init -backend=false -input=false -no-color)
            (cd "$d" && terraform fmt -recursive -check -no-color)
            (cd "$d" && terraform validate -no-color)
          done <<< "${{ steps.findtf.outputs.dirs }}"

      # ----- Python checks (run only if .py files exist) -----
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Black & Ruff
        run: |
          python -m pip install --upgrade pip
          pip install black ruff

      - name: Run Black (check)
        run: |
          if git ls-files '*.py' | grep -q .; then
            black --check .
          else
            echo "No Python files, skipping Black."
          fi

      - name: Run Ruff (lint)
        run: |
          if git ls-files '*.py' | grep -q .; then
            ruff check .
          else
            echo "No Python files, skipping Ruff."
          fi
